function out1 = phi12dd_file(dis_G1G2,disd_G1G2,phi12,phi12d,th1,th2)
%PHI12DD_FILE
%    OUT1 = PHI12DD_FILE(DIS_G1G2,DISD_G1G2,PHI12,PHI12D,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2016 21:57:42

t4 = cos(phi12);
t7 = cos(th1);
t9 = cos(th2);
t10 = t7.*(1.0./1.0e1);
t11 = t9.*(1.0./4.0e1);
t12 = dis_G1G2.*t4;
t13 = t10+t11+t12;
t2 = abs(t13);
t5 = sin(phi12);
t6 = sin(th1);
t8 = sin(th2);
t15 = t6.*(1.0./1.0e1);
t16 = t8.*(1.0./4.0e1);
t17 = dis_G1G2.*t5;
t18 = t15+t16+t17;
t3 = abs(t18);
t14 = t2.^2;
t19 = t3.^2;
t20 = t14+t19;
t21 = sqrt(t20);
t22 = t4.^2;
t23 = t5.^2;
t26 = t21.*2.0e3;
t24 = -t26+2.0e3;
t25 = exp(t24);
out1 = (t4.*t6.*(3.0./2.0e1)+t4.*t8.*(3.0./8.0e1)-t5.*t7.*(3.0./2.0e1)-t5.*t9.*(3.0./8.0e1)-disd_G1G2.*phi12d.*t22.*2.0-disd_G1G2.*phi12d.*t23.*2.0-t4.*t6.*t21.*(3.0./2.0e1)-t4.*t8.*t21.*(3.0./8.0e1)+t5.*t7.*t21.*(3.0./2.0e1)+t5.*t9.*t21.*(3.0./8.0e1)-disd_G1G2.*phi12d.*t22.*t25.*2.0-disd_G1G2.*phi12d.*t23.*t25.*2.0)./(dis_G1G2.*(t22+t23).*(t25+1.0));
