function eqn1 = test(coil1,coil2,coil3,dis_G1G2,dis_G1G3,disd_G1G2,...
    disd_G1G3,disdd_G1G2,disdd_G1G3,phi12,phi13,phi12d,phi13d,phi12dd,phi13dd,th1d)
%TEST
%    EQN1 = TEST(COIL1,COIL2,COIL3,DIS_G1G2,DIS_G1G3,DISD_G1G2,DISD_G1G3,DISDD_G1G2,DISDD_G1G3,PHI12,PHI13,PHI12D,PHI13D,PHI12DD,PHI13DD,TH1D)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2016 21:26:52

t2 = 0.0 == 0.0;
t3 = cos(phi12);
t4 = cos(phi13);
t5 = sin(phi12);
t6 = dis_G1G2.*phi12dd;
t7 = disd_G1G2.*phi12d.*2.0;
t8 = t6+t7;
t9 = phi12d.^2;
t10 = disdd_G1G2-dis_G1G2.*t9;
t11 = sin(phi13);
t12 = dis_G1G3.*phi13dd;
t13 = disd_G1G3.*phi13d.*2.0;
t14 = t12+t13;
t15 = phi13d.^2;
t16 = disdd_G1G3-dis_G1G3.*t15;
eqn1 = [t2,t2,coil1+coil2+coil3 == phi12d.*6.944444444444444e-4+phi13d.*6.944444444444444e-4+th1d.*(1.0./9.0e1)-dis_G1G2.*t3.*(t3.*t8.*(2.0./3.0)+t5.*t10.*(2.0./3.0))+dis_G1G2.*t5.*(t3.*t10.*(2.0./3.0)-t5.*t8.*(2.0./3.0))-dis_G1G3.*t4.*(t4.*t14.*(2.0./3.0)+t11.*t16.*(2.0./3.0))+dis_G1G3.*t11.*(t4.*t16.*(2.0./3.0)-t11.*t14.*(2.0./3.0))];
