function out1 = th2dd_EOM(coil2,dis_G1G2,phi12,th1,th2)
%TH2DD_EOM
%    OUT1 = TH2DD_EOM(COIL2,DIS_G1G2,PHI12,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    20-Oct-2016 22:25:19

t4 = cos(th1);
t6 = cos(th2);
t8 = t4.*(1.0./1.0e1);
t9 = t6.*(1.0./4.0e1);
t10 = cos(phi12);
t11 = dis_G1G2.*t10;
t12 = t8+t9+t11;
t2 = abs(t12);
t5 = sin(th2);
t7 = sin(th1);
t14 = t7.*(1.0./1.0e1);
t15 = t5.*(1.0./4.0e1);
t16 = sin(phi12);
t17 = dis_G1G2.*t16;
t18 = t14+t15+t17;
t3 = abs(t18);
t13 = t2.^2;
t19 = t3.^2;
t20 = t13+t19;
t21 = sqrt(t20);
t22 = t21.*-2.0e3+2.0e3;
t23 = exp(t22);
out1 = (coil2.*1.44e3+coil2.*t23.*1.44e3+t4.*t5.*3.6e1-t6.*t7.*3.6e1+dis_G1G2.*t5.*t10.*3.6e2-dis_G1G2.*t6.*t16.*3.6e2-t4.*t5.*t21.*3.6e1+t6.*t7.*t21.*3.6e1-dis_G1G2.*t5.*t10.*t21.*3.6e2+dis_G1G2.*t6.*t16.*t21.*3.6e2)./(t23+1.0);
