function out1 = disdd_G1G3_genEOM(d_G3T3,d_G1T13,dis_G1G3,ks,lo13,m3,phi13,phi13d,th1,th3)
%DISDD_G1G3_GENEOM
%    OUT1 = DISDD_G1G3_GENEOM(D_G3T3,D_G1T13,DIS_G1G3,KS,LO13,M3,PHI13,PHI13D,TH1,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Oct-2016 12:35:00

t5 = sin(phi13);
t7 = dis_G1G3.*t5;
t8 = sin(th3);
t9 = d_G3T3.*t8;
t10 = sin(th1);
t11 = d_G1T13.*t10;
t12 = -t7+t9+t11;
t2 = abs(t12);
t4 = cos(phi13);
t14 = dis_G1G3.*t4;
t15 = cos(th3);
t16 = d_G3T3.*t15;
t17 = cos(th1);
t18 = d_G1T13.*t17;
t19 = -t14+t16+t18;
t3 = abs(t19);
t6 = t4.^2;
t13 = t2.^2;
t20 = t3.^2;
t21 = t13+t20;
t22 = sqrt(t21);
t23 = t5.^2;
t24 = phi13d.^2;
t25 = lo13.*2.0e3;
t28 = t22.*2.0e3;
t26 = t25-t28;
t27 = exp(t26);
out1 = (dis_G1G3.*ks.*lo13.*t6+dis_G1G3.*ks.*lo13.*t23-dis_G1G3.*ks.*t6.*t22-dis_G1G3.*ks.*t22.*t23+dis_G1G3.*m3.*t6.*t24+dis_G1G3.*m3.*t23.*t24-d_G3T3.*ks.*lo13.*t5.*t8-d_G3T3.*ks.*lo13.*t4.*t15-d_G1T13.*ks.*lo13.*t5.*t10-d_G1T13.*ks.*lo13.*t4.*t17+d_G3T3.*ks.*t5.*t8.*t22+d_G3T3.*ks.*t4.*t15.*t22+d_G1T13.*ks.*t5.*t10.*t22+d_G1T13.*ks.*t4.*t17.*t22+dis_G1G3.*m3.*t6.*t24.*t27+dis_G1G3.*m3.*t23.*t24.*t27)./(m3.*(t6+t23).*(t27+1.0));
