function out1 = phi13dd_genEOM(d_G3T3,d_G1T13,dis_G1G3,disd_G1G3,ks,lo13,m3,phi13,phi13d,th1,th3)
%PHI13DD_GENEOM
%    OUT1 = PHI13DD_GENEOM(D_G3T3,D_G1T13,DIS_G1G3,DISD_G1G3,KS,LO13,M3,PHI13,PHI13D,TH1,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Oct-2016 12:35:00

t5 = sin(phi13);
t8 = sin(th3);
t10 = sin(th1);
t13 = dis_G1G3.*t5;
t14 = d_G3T3.*t8;
t15 = d_G1T13.*t10;
t16 = -t13+t14+t15;
t2 = abs(t16);
t4 = cos(phi13);
t9 = cos(th3);
t11 = cos(th1);
t18 = dis_G1G3.*t4;
t19 = d_G3T3.*t9;
t20 = d_G1T13.*t11;
t21 = -t18+t19+t20;
t3 = abs(t21);
t6 = t4.^2;
t7 = t5.^2;
t12 = lo13.*2.0e3;
t17 = t2.^2;
t22 = t3.^2;
t23 = t17+t22;
t24 = sqrt(t23);
t27 = t24.*2.0e3;
t25 = t12-t27;
t26 = exp(t25);
out1 = -(disd_G1G3.*m3.*phi13d.*t6.*2.0+disd_G1G3.*m3.*phi13d.*t7.*2.0+d_G3T3.*ks.*lo13.*t4.*t8-d_G3T3.*ks.*lo13.*t5.*t9+d_G1T13.*ks.*lo13.*t4.*t10-d_G1T13.*ks.*lo13.*t5.*t11+disd_G1G3.*m3.*phi13d.*t6.*t26.*2.0+disd_G1G3.*m3.*phi13d.*t7.*t26.*2.0-d_G3T3.*ks.*t4.*t8.*t24+d_G3T3.*ks.*t5.*t9.*t24-d_G1T13.*ks.*t4.*t10.*t24+d_G1T13.*ks.*t5.*t11.*t24)./(dis_G1G3.*m3.*(t6+t7).*(t26+1.0));
