function out1 = th1dd_genEOM(I_G1,coil1,d_G2T2,d_G3T3,d_G1T12,d_G1T13,dis_G1G2,dis_G1G3,ks,lo12,lo13,phi12,phi13,th1,th2,th3)
%TH1DD_GENEOM
%    OUT1 = TH1DD_GENEOM(I_G1,COIL1,D_G2T2,D_G3T3,D_G1T12,D_G1T13,DIS_G1G2,DIS_G1G3,KS,LO12,LO13,PHI12,PHI13,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Oct-2016 12:34:59

t4 = sin(th1);
t9 = sin(phi12);
t10 = dis_G1G2.*t9;
t11 = sin(th2);
t12 = d_G2T2.*t11;
t13 = d_G1T12.*t4;
t14 = t10+t12+t13;
t2 = abs(t14);
t6 = cos(th1);
t16 = cos(phi12);
t17 = dis_G1G2.*t16;
t18 = cos(th2);
t19 = d_G2T2.*t18;
t20 = d_G1T12.*t6;
t21 = t17+t19+t20;
t3 = abs(t21);
t28 = sin(phi13);
t29 = dis_G1G3.*t28;
t30 = sin(th3);
t31 = d_G3T3.*t30;
t32 = d_G1T13.*t4;
t33 = -t29+t31+t32;
t5 = abs(t33);
t35 = cos(phi13);
t36 = dis_G1G3.*t35;
t37 = cos(th3);
t38 = d_G3T3.*t37;
t39 = d_G1T13.*t6;
t40 = -t36+t38+t39;
t7 = abs(t40);
t8 = lo12.*2.0e3;
t15 = t2.^2;
t22 = t3.^2;
t23 = t15+t22;
t24 = sqrt(t23);
t46 = t24.*2.0e3;
t25 = t8-t46;
t26 = exp(t25);
t27 = lo13.*2.0e3;
t34 = t5.^2;
t41 = t7.^2;
t42 = t34+t41;
t43 = sqrt(t42);
t47 = t43.*2.0e3;
t44 = t27-t47;
t45 = exp(t44);
out1 = (coil1+coil1.*t26+coil1.*t45+coil1.*t26.*t45-d_G2T2.*d_G1T12.*ks.*lo12.*t6.*t11+d_G2T2.*d_G1T12.*ks.*lo12.*t4.*t18-d_G3T3.*d_G1T13.*ks.*lo13.*t6.*t30+d_G3T3.*d_G1T13.*ks.*lo13.*t4.*t37-d_G1T12.*dis_G1G2.*ks.*lo12.*t6.*t9+d_G1T12.*dis_G1G2.*ks.*lo12.*t4.*t16+d_G1T13.*dis_G1G3.*ks.*lo13.*t6.*t28-d_G1T13.*dis_G1G3.*ks.*lo13.*t4.*t35+d_G2T2.*d_G1T12.*ks.*t6.*t11.*t24-d_G2T2.*d_G1T12.*ks.*t4.*t18.*t24+d_G3T3.*d_G1T13.*ks.*t6.*t30.*t43-d_G3T3.*d_G1T13.*ks.*t4.*t37.*t43+d_G1T12.*dis_G1G2.*ks.*t6.*t9.*t24-d_G1T12.*dis_G1G2.*ks.*t4.*t16.*t24-d_G1T13.*dis_G1G3.*ks.*t6.*t28.*t43+d_G1T13.*dis_G1G3.*ks.*t4.*t35.*t43-d_G2T2.*d_G1T12.*ks.*lo12.*t6.*t11.*t45+d_G2T2.*d_G1T12.*ks.*lo12.*t4.*t18.*t45-d_G3T3.*d_G1T13.*ks.*lo13.*t6.*t26.*t30+d_G3T3.*d_G1T13.*ks.*lo13.*t4.*t26.*t37-d_G1T12.*dis_G1G2.*ks.*lo12.*t6.*t9.*t45+d_G1T13.*dis_G1G3.*ks.*lo13.*t6.*t26.*t28+d_G1T12.*dis_G1G2.*ks.*lo12.*t4.*t16.*t45-d_G1T13.*dis_G1G3.*ks.*lo13.*t4.*t26.*t35+d_G2T2.*d_G1T12.*ks.*t6.*t11.*t24.*t45-d_G2T2.*d_G1T12.*ks.*t4.*t18.*t24.*t45+d_G3T3.*d_G1T13.*ks.*t6.*t26.*t30.*t43-d_G3T3.*d_G1T13.*ks.*t4.*t26.*t37.*t43+d_G1T12.*dis_G1G2.*ks.*t6.*t9.*t24.*t45-d_G1T12.*dis_G1G2.*ks.*t4.*t16.*t24.*t45-d_G1T13.*dis_G1G3.*ks.*t6.*t26.*t28.*t43+d_G1T13.*dis_G1G3.*ks.*t4.*t26.*t35.*t43)./(I_G1.*(t26+1.0).*(t45+1.0));
