function out1 = th2dd_genEOM(I_G2,coil2,d_G2T2,d_G1T12,dis_G1G2,ks,lo12,phi12,th1,th2)
%TH2DD_GENEOM
%    OUT1 = TH2DD_GENEOM(I_G2,COIL2,D_G2T2,D_G1T12,DIS_G1G2,KS,LO12,PHI12,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Oct-2016 12:34:59

t5 = sin(phi12);
t6 = dis_G1G2.*t5;
t7 = sin(th2);
t8 = d_G2T2.*t7;
t9 = sin(th1);
t10 = d_G1T12.*t9;
t11 = t6+t8+t10;
t2 = abs(t11);
t13 = cos(phi12);
t14 = dis_G1G2.*t13;
t15 = cos(th2);
t16 = d_G2T2.*t15;
t17 = cos(th1);
t18 = d_G1T12.*t17;
t19 = t14+t16+t18;
t3 = abs(t19);
t4 = lo12.*2.0e3;
t12 = t2.^2;
t20 = t3.^2;
t21 = t12+t20;
t22 = sqrt(t21);
t23 = t4-t22.*2.0e3;
t24 = exp(t23);
out1 = (coil2+coil2.*t24+d_G2T2.*d_G1T12.*ks.*lo12.*t7.*t17-d_G2T2.*d_G1T12.*ks.*lo12.*t9.*t15-d_G2T2.*dis_G1G2.*ks.*lo12.*t5.*t15+d_G2T2.*dis_G1G2.*ks.*lo12.*t7.*t13-d_G2T2.*d_G1T12.*ks.*t7.*t17.*t22+d_G2T2.*d_G1T12.*ks.*t9.*t15.*t22+d_G2T2.*dis_G1G2.*ks.*t5.*t15.*t22-d_G2T2.*dis_G1G2.*ks.*t7.*t13.*t22)./(I_G2.*(t24+1.0));
