function out1 = th3dd_genEOM(I_G3,coil3,d_G3T3,d_G1T13,dis_G1G3,ks,lo13,phi13,th1,th3)
%TH3DD_GENEOM
%    OUT1 = TH3DD_GENEOM(I_G3,COIL3,D_G3T3,D_G1T13,DIS_G1G3,KS,LO13,PHI13,TH1,TH3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Oct-2016 12:34:59

t5 = sin(phi13);
t6 = dis_G1G3.*t5;
t7 = sin(th3);
t8 = d_G3T3.*t7;
t9 = sin(th1);
t10 = d_G1T13.*t9;
t11 = -t6+t8+t10;
t2 = abs(t11);
t13 = cos(phi13);
t14 = dis_G1G3.*t13;
t15 = cos(th3);
t16 = d_G3T3.*t15;
t17 = cos(th1);
t18 = d_G1T13.*t17;
t19 = -t14+t16+t18;
t3 = abs(t19);
t4 = lo13.*2.0e3;
t12 = t2.^2;
t20 = t3.^2;
t21 = t12+t20;
t22 = sqrt(t21);
t23 = t4-t22.*2.0e3;
t24 = exp(t23);
out1 = (coil3+coil3.*t24+d_G3T3.*d_G1T13.*ks.*lo13.*t7.*t17-d_G3T3.*d_G1T13.*ks.*lo13.*t9.*t15+d_G3T3.*dis_G1G3.*ks.*lo13.*t5.*t15-d_G3T3.*dis_G1G3.*ks.*lo13.*t7.*t13-d_G3T3.*d_G1T13.*ks.*t7.*t17.*t22+d_G3T3.*d_G1T13.*ks.*t9.*t15.*t22-d_G3T3.*dis_G1G3.*ks.*t5.*t15.*t22+d_G3T3.*dis_G1G3.*ks.*t7.*t13.*t22)./(I_G3.*(t24+1.0));
